# Generated by Django 5.1 on 2024-10-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_chefoffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefoffering',
            name='category',
            field=models.CharField(choices=[('savory', 'Savory'), ('sweet', 'Sweet')], max_length=100),
        ),
    ]
