# Generated by Django 5.1 on 2024-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_alter_chefoffering_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefoffering',
            name='specialty',
        ),
        migrations.AddField(
            model_name='chefoffering',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
