# Generated by Django 5.1 on 2024-11-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_remove_chefoffering_specialty_chefoffering_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefoffering',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dish_images/')),
                ('chef_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='dash.chefoffering')),
            ],
        ),
    ]
