# Generated by Django 5.1 on 2024-11-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_alter_chefoffering_image_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
