# Generated by Django 5.1 on 2024-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_user_additional_details_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
